global:
  scrape_interval: 600s

scrape_configs:
  - job_name: 'nestjs_apps'
    static_configs:
      - targets:
        - 'api-gateway:3001'
        - 'auth-service:3002'
        - 'product-service:3003'

  - job_name: 'observability'
    static_configs:
      - targets:
        - 'loki:3100'
        - 'tempo:3200'